using System.Collections.Generic;
using UnityEngine;

namespace GoatDescent
{
    public sealed class MountainPrototypeBuilder : MonoBehaviour
    {
        private Transform mountain, ledges, vegetation, scenery;
        private Material rockLight, rockMid, rockDark, ledgeTop, grass, trunk, needles, needlesSun, heather, cloud, mist, snow, water, foam, skyGradient, trailMarker, fire;
        private PhysicsMaterial surefootedStone;
        private Texture2D pixelDetail;
        private Vector3 finishPosition;
        private static readonly Vector2[] MountainRings =
        {
            new Vector2(-2f, 88f), new Vector2(12f, 84f), new Vector2(27f, 76f), new Vector2(45f, 65f),
            new Vector2(64f, 55f), new Vector2(82f, 44f), new Vector2(99f, 34f), new Vector2(114f, 23f),
            new Vector2(125f, 12f), new Vector2(132f, 3.5f)
        };
        // Summit-to-basin height is roughly 136 m; the playable descent itself is ~132 m.
        public static readonly Vector3 SpawnPoint = new Vector3(0f, 133.5f, 0f);

        private void Awake()
        {
            CreateMaterials();
            mountain = new GameObject("MountainMass").transform; mountain.SetParent(transform);
            ledges = new GameObject("Ledges — guaranteed descent route").transform; ledges.SetParent(transform);
            vegetation = new GameObject("Vegetation").transform; vegetation.SetParent(transform);
            scenery = new GameObject("Atmosphere and distant ranges").transform; scenery.SetParent(transform);
            BuildMountain();
            BuildRoute();
            BuildVegetation();
            BuildScenery();
            BuildFinish();
            CreatePlayer();
            CreateLighting();
            // The mountain is generated by transforms in Awake. Sync once so the first physics tick sees every platform.
            Physics.SyncTransforms();
        }

        private void CreateMaterials()
        {
            pixelDetail = CreatePixelDetailTexture();
            rockLight = MakeRockMaterial("Weathered stone", new Color(.19f, .20f, .14f), new Color(.55f, .47f, .31f));
            rockMid = MakeRockMaterial("Moss shadow stone", new Color(.09f, .14f, .105f), new Color(.34f, .39f, .26f));
            rockDark = MakeRockMaterial("Deep forest stone", new Color(.035f, .07f, .045f), new Color(.18f, .24f, .15f));
            ledgeTop = MakeRockMaterial("Mossy route stone", new Color(.09f, .20f, .05f), new Color(.38f, .53f, .16f));
            grass = MakeRockMaterial("Meadow grass", new Color(.08f, .17f, .03f), new Color(.35f, .50f, .11f), false);
            trunk = MakeMaterial("Pine trunk", new Color(.15f, .075f, .03f));
            needles = MakeMaterial("Pine needles", new Color(.018f, .11f, .035f));
            needlesSun = MakeMaterial("Sun-tipped pine needles", new Color(.065f, .19f, .055f));
            heather = MakeMaterial("Heather bloom", new Color(.32f, .12f, .24f));
            cloud = MakeMaterial("Storm-lit cloud", new Color(.75f, .79f, .70f));
            mist = MakeTransparentMaterial("Valley mist", new Color(.57f, .66f, .55f, .25f));
            snow = MakeMaterial("Wind-packed summit snow", new Color(.79f, .87f, .84f));
            water = MakeTransparentMaterial("Glacier waterfall", new Color(.27f, .62f, .68f, .58f));
            foam = MakeTransparentMaterial("Waterfall foam", new Color(.82f, .94f, .89f, .72f));
            trailMarker = MakeMaterial("Warm trail marker", new Color(.88f, .19f, .035f));
            fire = MakeMaterial("Ember flame", new Color(1f, .24f, .025f)); fire.EnableKeyword("_EMISSION"); fire.SetColor("_EmissionColor", new Color(1f, .075f, .005f) * 1.8f);
            surefootedStone = new PhysicsMaterial("Surefooted route stone")
            {
                dynamicFriction = .88f,
                staticFriction = 1f,
                frictionCombine = PhysicsMaterialCombine.Maximum,
                bounceCombine = PhysicsMaterialCombine.Minimum
            };
            ConfigureRockBiome(rockLight, new Color(.28f, .40f, .12f), .26f, 8f, 85f);
            ConfigureRockBiome(rockMid, new Color(.18f, .31f, .09f), .42f, 5f, 92f);
            ConfigureRockBiome(rockDark, new Color(.08f, .20f, .06f), .18f, -3f, 68f);
            ConfigureRockBiome(ledgeTop, new Color(.28f, .48f, .08f), .58f, -5f, 108f);
            var skyShader = Shader.Find("GoatDescent/Stylized Sky");
            if (skyShader != null)
            {
                skyGradient = new Material(skyShader) { name = "Alpine gradient sky" };
                skyGradient.SetColor("_HorizonColor", new Color(.38f, .49f, .37f));
                skyGradient.SetColor("_ZenithColor", new Color(.04f, .105f, .16f));
                skyGradient.SetColor("_SunColor", new Color(1f, .45f, .16f));
                skyGradient.SetVector("_SunDirection", new Vector4(-.42f, .50f, .45f, 0f));
            }
        }

        private Material MakeMaterial(string name, Color color)
        {
            var material = new Material(Shader.Find("Standard")) { name = name, color = color };
            material.SetFloat("_Glossiness", .12f);
            return material;
        }

        private Material MakeTransparentMaterial(string name, Color color)
        {
            var material = MakeMaterial(name, color);
            material.SetFloat("_Mode", 3f);
            material.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
            material.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
            material.SetInt("_ZWrite", 0);
            material.DisableKeyword("_ALPHATEST_ON");
            material.EnableKeyword("_ALPHABLEND_ON");
            material.DisableKeyword("_ALPHAPREMULTIPLY_ON");
            material.renderQueue = 3000;
            return material;
        }

        private void ConfigureRockBiome(Material material, Color mossColor, float mossStrength, float mossLow, float mossHigh)
        {
            if (!material || !material.HasProperty("_MossColor")) return;
            material.SetColor("_MossColor", mossColor);
            material.SetFloat("_MossStrength", mossStrength);
            material.SetFloat("_MossLow", mossLow);
            material.SetFloat("_MossHigh", mossHigh);
            material.SetFloat("_MossFade", 15f);
            material.SetFloat("_RimStrength", .16f);
        }

        private Material MakeRockMaterial(string name, Color shadow, Color sunlit, bool receivesSnow = true)
        {
            var shader = Shader.Find("GoatDescent/Stylized Rock");
            if (shader == null) return MakeMaterial(name, sunlit);
            var material = new Material(shader) { name = name };
            material.SetColor("_BaseColor", shadow);
            material.SetColor("_AccentColor", sunlit);
            material.SetColor("_SnowColor", new Color(.88f, .95f, .97f));
            material.SetFloat("_SnowHeight", receivesSnow ? 108f : 10000f);
            material.SetFloat("_SnowBlend", 11f);
            material.SetTexture("_DetailTex", pixelDetail);
            material.SetFloat("_DetailScale", .085f);
            material.SetFloat("_DetailStrength", .22f);
            return material;
        }

        private Texture2D CreatePixelDetailTexture()
        {
            const int size = 32;
            var texture = new Texture2D(size, size, TextureFormat.RGB24, false) { name = "Generated low-res surface detail", filterMode = FilterMode.Point, wrapMode = TextureWrapMode.Repeat };
            var pixels = new Color[size * size];
            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size; x++)
                {
                    float hash = Mathf.Repeat(Mathf.Sin(x * 17.17f + y * 31.31f) * 43758.5453f, 1f);
                    float tone = hash > .88f ? .56f : hash < .14f ? .78f : .95f;
                    pixels[y * size + x] = new Color(tone, tone, tone);
                }
            }
            texture.SetPixels(pixels); texture.Apply(false, true);
            return texture;
        }

        private void BuildMountain()
        {
            // A single terraced shell reads as a climbable mountain, not a collection of floating primitive cones.
            CreateMountainShell();
            CreateCliffSpines();
            CreateStrataRibbons();
            CreateSnowCaps();
            CreateLandingRock("Summit", new Vector3(0, 131.4f, 0), new Vector3(6f, 1f, 5.5f), ledgeTop, 8f);
            CreateCampfire(new Vector3(-1.55f, 132.1f, .95f), "Summit watchfire", .85f);
            CreateFlatRock("Base basin", new Vector3(0, -3f, 0), new Vector3(155f, 3f, 145f), grass, 0f);
        }

        private void CreateMountainShell()
        {
            var rings = MountainRings;
            const int sides = 32;
            var vertices = new List<Vector3>();
            var triangles = new List<int>();
            for (int ring = 0; ring < rings.Length; ring++)
            {
                for (int side = 0; side < sides; side++)
                {
                    float a = (side * 360f / sides + ring * 3.8f) * Mathf.Deg2Rad;
                    float ridgeNoise = Mathf.PerlinNoise(side * .19f + 4.1f, ring * .41f + .7f);
                    float spur = Mathf.Sin(a * 5f + ring * .8f) * (ring > 2 && ring < rings.Length - 2 ? 3.5f : 1.2f);
                    float noise = .87f + ridgeNoise * .20f + spur / rings[ring].y;
                    float yJitter = ring == 0 || ring == rings.Length - 1 ? 0f : (Mathf.PerlinNoise(side * .37f + 7f, ring * .67f) - .5f) * 4.2f;
                    vertices.Add(new Vector3(Mathf.Cos(a) * rings[ring].y * noise, rings[ring].x + yJitter, Mathf.Sin(a) * rings[ring].y * noise));
                }
            }
            for (int ring = 0; ring < rings.Length - 1; ring++)
            {
                for (int side = 0; side < sides; side++)
                {
                    int next = (side + 1) % sides;
                    int a = ring * sides + side, b = ring * sides + next, c = (ring + 1) * sides + side, d = (ring + 1) * sides + next;
                    triangles.Add(a); triangles.Add(c); triangles.Add(b);
                    triangles.Add(b); triangles.Add(c); triangles.Add(d);
                }
            }
            int summit = vertices.Count;
            vertices.Add(new Vector3(0f, 131.6f, 0f));
            int topRing = (rings.Length - 1) * sides;
            for (int side = 0; side < sides; side++) { int next = (side + 1) % sides; triangles.Add(topRing + side); triangles.Add(summit); triangles.Add(topRing + next); }
            var mesh = new Mesh { name = "Faceted alpine mountain mesh" };
            mesh.SetVertices(vertices); mesh.SetTriangles(triangles, 0); mesh.RecalculateBounds();
            var mountainObject = new GameObject("Faceted alpine mountain shell"); mountainObject.transform.SetParent(mountain);
            mountainObject.AddComponent<MeshFilter>().sharedMesh = mesh;
            mountainObject.AddComponent<MeshRenderer>().sharedMaterial = rockMid;
            mountainObject.AddComponent<MeshCollider>().sharedMesh = mesh;
        }

        private void CreateCliffSpines()
        {
            // Long vertical spines break the even cone outline and produce readable Valheim-like escarpments from afar.
            for (int i = 0; i < 13; i++)
            {
                float angle = (i * 47f + 18f) * Mathf.Deg2Rad;
                float radius = 23f + (i % 5) * 6f;
                float surface = GetMountainSurfaceHeight(radius);
                float height = 9f + (i % 4) * 4f;
                Vector3 p = new Vector3(Mathf.Cos(angle) * radius, surface + height * .07f, Mathf.Sin(angle) * radius);
                var spine = CreateRock("Weather-cut cliff spine", p, new Vector3(3.4f + (i % 3) * .9f, height, 7f + (i % 4) * 1.1f), i % 3 == 0 ? rockLight : rockDark, 6, i * 47f);
                spine.transform.localRotation = Quaternion.Euler(i % 2 == 0 ? 7f : -6f, i * 47f, i % 3 == 0 ? 11f : -8f);
            }
        }

        private void CreateStrataRibbons()
        {
            // Thin bands catch the low sun and make the mountain read as layered stone instead of one procedural cone.
            for (int i = 0; i < 29; i++)
            {
                float a = (i * 79f + 14f) * Mathf.Deg2Rad;
                float radius = 27f + (i % 8) * 5.7f;
                float height = GetMountainSurfaceHeight(radius);
                Vector3 p = new Vector3(Mathf.Cos(a) * radius * 1.08f, height + .42f, Mathf.Sin(a) * radius * 1.08f);
                var ribbon = CreateRock("Sun-caught strata", p, new Vector3(5.2f + (i % 3), .65f + (i % 2) * .22f, 2.1f + (i % 4) * .36f), i % 3 == 0 ? rockLight : rockMid, 6, i * 79f, false);
                ribbon.transform.SetParent(scenery);
            }
        }

        private void CreateSnowCaps()
        {
            // Sparse, wind-swept snow shelves keep the summit cold without covering the dark climbable stone.
            for (int i = 0; i < 18; i++)
            {
                float angle = (i * 61f + 9f) * Mathf.Deg2Rad;
                float radius = 5.5f + (i % 5) * 3.3f;
                float y = GetMountainSurfaceHeight(radius) + .35f;
                var patch = CreateLandingRock("Wind-carved snow shelf", new Vector3(Mathf.Cos(angle) * radius, y, Mathf.Sin(angle) * radius), new Vector3(3.2f + (i % 3) * .7f, .16f, 2.1f + (i % 2) * .55f), snow, i * 61f, false);
                patch.transform.SetParent(scenery);
            }
        }

        private void BuildRoute()
        {
            // Sample height from the inner slope, then place the landing beyond the widest noisy silhouette.
            // Sampling height from the already-offset point put upper landings back inside the new broad mountain.
            const int routeCount = 30;
            var route = new Vector3[routeCount];
            for (int i = 0; i < route.Length; i++)
            {
                // A gentle turn keeps consecutive ledges within one grounded jump, including near the wide base.
                float a = (117f + i * 2.4f) * Mathf.Deg2Rad;
                float t = i / (float)(route.Length - 1);
                float terraceHeight = Mathf.Lerp(129.8f, -1.35f, t);
                float coreRadius = GetMountainCoreRadiusAtHeight(terraceHeight);
                float outsideRadius = coreRadius * 1.23f + 4.2f;
                route[i] = new Vector3(Mathf.Cos(a) * outsideRadius, terraceHeight + 1.35f, Mathf.Sin(a) * outsideRadius);
            }
            finishPosition = route[route.Length - 1];
            for (int i = 0; i < route.Length; i++)
            {
                float width = i == 3 || i == 7 ? 3.5f : 4.6f;
                CreateLedge("Route ledge " + (i + 1), route[i], new Vector3(width, .9f, width * .8f), i % 3 == 0 ? ledgeTop : rockLight, i * 23f);
                if (i > 0 && i % 3 == 0) CreateTrailMarker(route[i], i * 23f);
                if (i % 4 == 1) CreateRouteBeacon(route[i], i * 23f);
                if (i < route.Length - 2 && i % 2 == 0)
                {
                    Vector3 between = Vector3.Lerp(route[i], route[i + 2], .58f);
                    Vector3 horizontal = Vector3.ProjectOnPlane(between, Vector3.up);
                    Vector3 outward = horizontal.sqrMagnitude > .001f ? horizontal.normalized : Vector3.forward;
                    float optionalRadius = horizontal.magnitude + 3.4f;
                    Vector3 optional = outward * optionalRadius;
                    optional.y = Mathf.Lerp(route[i].y, route[i + 2].y, .58f) - .45f;
                    CreateLedge("Risk shortcut " + (i + 1), optional, new Vector3(2.1f, .7f, 1.8f), rockLight, i * 37f);
                }
            }
        }

        private void BuildVegetation()
        {
            // Tall, dark pine silhouettes make the medium distance readable and give the route a Nordic forest mood.
            for (int i = 0; i < 78; i++)
            {
                float a = i * 137.5f * Mathf.Deg2Rad;
                float r = 20f + (i % 9) * 6.7f;
                float y = GetMountainSurfaceHeight(r) - .15f;
                CreatePine(new Vector3(Mathf.Cos(a) * r, y, Mathf.Sin(a) * r), 5.4f + (i % 4) * 1.55f);
            }
            for (int i = 0; i < 124; i++)
            {
                float a = i * 71f * Mathf.Deg2Rad;
                float r = 15f + (i % 10) * 6.4f;
                CreateAlpineTuft(new Vector3(Mathf.Cos(a) * r, GetMountainSurfaceHeight(r), Mathf.Sin(a) * r), .45f + (i % 4) * .13f, i * 19f);
            }
            for (int i = 0; i < 46; i++)
            {
                float a = i * 103f * Mathf.Deg2Rad;
                float r = 24f + (i % 8) * 6.2f;
                var boulder = CreateRock("Mossy field boulder", new Vector3(Mathf.Cos(a) * r, GetMountainSurfaceHeight(r) - .5f, Mathf.Sin(a) * r), new Vector3(2.2f + (i % 3), 1.8f + (i % 2) * .7f, 2f + (i % 4) * .25f), i % 3 == 0 ? ledgeTop : rockLight, 5, i * 31f, false);
                boulder.transform.SetParent(vegetation);
            }
            for (int i = 0; i < 82; i++)
            {
                float a = i * 93f * Mathf.Deg2Rad;
                float r = 19f + (i % 11) * 5.4f;
                CreateShrub(new Vector3(Mathf.Cos(a) * r, GetMountainSurfaceHeight(r), Mathf.Sin(a) * r), .55f + (i % 3) * .2f, i * 27f);
            }
            // Talus makes the transition between dark forest and bare upper stone feel naturally eroded, not tiled.
            for (int i = 0; i < 112; i++)
            {
                float a = i * 137.5f * Mathf.Deg2Rad;
                float r = 31f + (i % 12) * 3.35f;
                float size = .42f + (i % 5) * .16f;
                var talus = CreateRock("Loose talus stone", new Vector3(Mathf.Cos(a) * r, GetMountainSurfaceHeight(r) + size * .08f, Mathf.Sin(a) * r), new Vector3(size * 1.5f, size, size * 1.28f), i % 4 == 0 ? rockLight : rockMid, 5, i * 31f, false);
                talus.transform.SetParent(vegetation);
            }
        }

        private float GetMountainSurfaceHeight(float radius)
        {
            if (radius >= MountainRings[0].y) return MountainRings[0].x;
            for (int i = 0; i < MountainRings.Length - 1; i++)
            {
                if (radius >= MountainRings[i + 1].y)
                {
                    float t = Mathf.InverseLerp(MountainRings[i].y, MountainRings[i + 1].y, radius);
                    return Mathf.Lerp(MountainRings[i].x, MountainRings[i + 1].x, t);
                }
            }
            return MountainRings[MountainRings.Length - 1].x;
        }

        private float GetMountainCoreRadiusAtHeight(float height)
        {
            if (height <= MountainRings[0].x) return MountainRings[0].y;
            for (int i = 0; i < MountainRings.Length - 1; i++)
            {
                if (height <= MountainRings[i + 1].x)
                {
                    float t = Mathf.InverseLerp(MountainRings[i].x, MountainRings[i + 1].x, height);
                    return Mathf.Lerp(MountainRings[i].y, MountainRings[i + 1].y, t);
                }
            }
            return MountainRings[MountainRings.Length - 1].y;
        }

        private void BuildScenery()
        {
            CreateSkyDome();
            CreateDistantRanges();
            CreateValleyMist();
            CreateWaterfall();
            // Cloud banks stay above the descent line and leave the navigation view uncluttered.
            var cloudPositions = new[]
            {
                new Vector3(5f, 160f, 48f), new Vector3(-38f, 164f, 92f), new Vector3(58f, 152f, 92f),
                new Vector3(-108f, 145f, -18f), new Vector3(30f, 174f, 165f)
            };
            for (int i = 0; i < cloudPositions.Length; i++) CreateCloudBank(cloudPositions[i], 1f + (i % 3) * .18f, i * 29f);
        }

        private void CreateDistantRanges()
        {
            // Silhouette-only peaks make the playable mountain feel like one summit in a larger world.
            var ranges = new[]
            {
                new Vector3(-215f, 13f, 195f), new Vector3(165f, 8f, 230f), new Vector3(235f, 4f, -145f), new Vector3(-245f, 7f, -120f)
            };
            for (int i = 0; i < ranges.Length; i++)
            {
                var peak = CreateRock("Distant mountain silhouette", ranges[i], new Vector3(92f + (i % 2) * 27f, 92f + (i % 3) * 18f, 72f + (i % 2) * 20f), rockDark, 9, i * 34f, false);
                peak.transform.SetParent(scenery);
                for (int j = 0; j < 3; j++)
                {
                    Vector3 offset = new Vector3((j - 1) * 38f, -13f - j * 5f, (j % 2 == 0 ? 19f : -17f));
                    var shoulder = CreateRock("Distant ridge shoulder", ranges[i] + offset, new Vector3(58f, 61f - j * 7f, 50f), rockMid, 7, i * 34f + j * 23f, false);
                    shoulder.transform.SetParent(scenery);
                }
            }
        }

        private void CreateValleyMist()
        {
            for (int i = 0; i < 8; i++)
            {
                float a = i * 47f * Mathf.Deg2Rad;
                var bank = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                bank.name = "Low rolling valley mist";
                bank.transform.SetParent(scenery);
                bank.transform.SetPositionAndRotation(new Vector3(Mathf.Cos(a) * (75f + (i % 3) * 13f), 12f + (i % 2) * 5f, Mathf.Sin(a) * (75f + (i % 3) * 13f)), Quaternion.Euler(0f, i * 47f, 0f));
                bank.transform.localScale = new Vector3(42f, 5.5f, 24f);
                bank.GetComponent<Renderer>().sharedMaterial = mist;
                Destroy(bank.GetComponent<Collider>());
            }
        }

        private void CreateWaterfall()
        {
            // One cold vertical accent gives the far face a landmark and contrasts the route's warm beacons.
            const float angleDegrees = 54f;
            Vector3 outward = new Vector3(Mathf.Cos(angleDegrees * Mathf.Deg2Rad), 0f, Mathf.Sin(angleDegrees * Mathf.Deg2Rad));
            float sourceRadius = 48f;
            float sourceY = GetMountainSurfaceHeight(sourceRadius) + 5f;
            var root = new GameObject("Glacier waterfall"); root.transform.SetParent(scenery); root.transform.position = outward * (sourceRadius * 1.13f) + Vector3.up * sourceY;
            for (int i = 0; i < 5; i++)
            {
                var stream = GameObject.CreatePrimitive(PrimitiveType.Cube);
                stream.name = "Waterfall cascade"; stream.transform.SetParent(root.transform);
                stream.transform.localPosition = new Vector3((i % 2 == 0 ? -.22f : .18f), -i * 6.7f, -.16f);
                stream.transform.localRotation = Quaternion.Euler(i % 2 == 0 ? 4f : -5f, angleDegrees + 90f, 0f);
                stream.transform.localScale = new Vector3(1.05f + (i % 3) * .18f, 7.1f, .11f);
                stream.GetComponent<Renderer>().sharedMaterial = water;
                Destroy(stream.GetComponent<Collider>());
            }
            var spray = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            spray.name = "Waterfall spray"; spray.transform.SetParent(root.transform); spray.transform.localPosition = Vector3.down * 33.8f; spray.transform.localScale = new Vector3(5.4f, 1.1f, 3.5f); spray.GetComponent<Renderer>().sharedMaterial = foam; Destroy(spray.GetComponent<Collider>());
        }

        private void CreateSkyDome()
        {
            if (skyGradient == null) return;
            var dome = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            dome.name = "Stylized alpine sky dome";
            dome.transform.SetParent(scenery);
            dome.transform.localPosition = new Vector3(0f, 70f, 0f);
            dome.transform.localScale = Vector3.one * 620f;
            dome.GetComponent<Renderer>().sharedMaterial = skyGradient;
            Destroy(dome.GetComponent<Collider>());
        }

        private void CreateCloudBank(Vector3 center, float scale, float rotation)
        {
            var offsets = new[] { new Vector3(-5f, 0f, 0f), new Vector3(0f, 1.4f, 1f), new Vector3(5f, -.3f, -.5f) };
            for (int i = 0; i < offsets.Length; i++)
            {
                var puff = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                puff.name = "Sunlit cloud puff";
                puff.transform.SetParent(scenery);
                puff.transform.SetPositionAndRotation(center + offsets[i] * scale, Quaternion.Euler(0f, rotation + i * 17f, 0f));
                puff.transform.localScale = new Vector3(11f, 5f, 7f) * scale;
                puff.GetComponent<Renderer>().sharedMaterial = cloud;
                Destroy(puff.GetComponent<Collider>());
            }
        }

        private void BuildFinish()
        {
            var finish = CreateLandingRock("Finish meadow", finishPosition + new Vector3(0f, -.8f, 0f), new Vector3(12, .5f, 10), grass, 12);
            var marker = GameObject.CreatePrimitive(PrimitiveType.Cylinder); marker.name = "Finish cairn"; marker.transform.SetPositionAndRotation(finishPosition + Vector3.up * .8f, Quaternion.identity); marker.transform.localScale = new Vector3(.45f, 1.8f, .45f); marker.GetComponent<Renderer>().sharedMaterial = rockLight;
            CreateCampfire(finishPosition + new Vector3(2.2f, .15f, -1.2f), "Finish hearth", 1.15f);
            finish.transform.SetParent(ledges);
        }

        private void CreateCampfire(Vector3 position, string name, float scale)
        {
            var root = new GameObject(name); root.transform.SetParent(scenery); root.transform.position = position;
            for (int i = 0; i < 3; i++)
            {
                var log = GameObject.CreatePrimitive(PrimitiveType.Cube); log.name = "Charred log"; log.transform.SetParent(root.transform); log.transform.localPosition = Vector3.up * .08f; log.transform.localRotation = Quaternion.Euler(0f, i * 60f, 14f); log.transform.localScale = new Vector3(.18f, .12f, 1.1f) * scale; log.GetComponent<Renderer>().sharedMaterial = trunk; Destroy(log.GetComponent<Collider>());
            }
            var flame = GameObject.CreatePrimitive(PrimitiveType.Sphere); flame.name = "Stylized flame"; flame.transform.SetParent(root.transform); flame.transform.localPosition = Vector3.up * .47f * scale; flame.transform.localScale = new Vector3(.32f, .75f, .32f) * scale; flame.GetComponent<Renderer>().sharedMaterial = fire; Destroy(flame.GetComponent<Collider>());
            var ember = GameObject.CreatePrimitive(PrimitiveType.Sphere); ember.name = "Hot ember"; ember.transform.SetParent(root.transform); ember.transform.localPosition = new Vector3(.12f, .88f, -.04f) * scale; ember.transform.localScale = Vector3.one * .10f * scale; ember.GetComponent<Renderer>().sharedMaterial = fire; Destroy(ember.GetComponent<Collider>());
            var glow = root.AddComponent<Light>(); glow.type = LightType.Point; glow.range = 8f * scale; glow.intensity = 2.1f * scale; glow.color = new Color(1f, .24f, .045f); glow.shadows = LightShadows.Soft;
        }

        private void CreatePlayer()
        {
            var goat = new GameObject("Mountain Goat"); goat.transform.position = SpawnPoint;
            int playerLayer = LayerMask.NameToLayer("Player"); if (playerLayer >= 0) goat.layer = playerLayer;
            var body = goat.AddComponent<Rigidbody>(); body.mass = 72f; body.interpolation = RigidbodyInterpolation.Interpolate; body.collisionDetectionMode = CollisionDetectionMode.ContinuousDynamic; body.constraints = RigidbodyConstraints.FreezeRotation;
            var capsule = goat.AddComponent<CapsuleCollider>(); capsule.radius = .48f; capsule.height = 1.15f; capsule.center = new Vector3(0, .58f, 0);
            var detector = goat.AddComponent<GoatGroundDetector>();
            var controller = goat.AddComponent<GoatController>(); controller.Configure(body, detector);
            goat.AddComponent<GoatJumpController>().Configure(controller, detector);
            goat.AddComponent<GoatLandingAssist>().Configure(body, detector);
            goat.AddComponent<GoatVisualController>().Configure(body, detector);
            goat.AddComponent<RespawnController>().Configure(body, SpawnPoint);
            var cam = new GameObject("Third Person Goat Camera"); cam.tag = "MainCamera";
            var camera = cam.AddComponent<Camera>(); camera.clearFlags = CameraClearFlags.Skybox; camera.backgroundColor = new Color(.10f, .17f, .15f); camera.farClipPlane = 540f; camera.allowHDR = true; camera.allowMSAA = true;
            cam.AddComponent<ThirdPersonGoatCamera>().Configure(goat.transform);
        }

        private void CreateLighting()
        {
            var skyShader = Shader.Find("Skybox/Procedural");
            if (skyShader != null)
            {
                var sky = new Material(skyShader);
                sky.SetColor("_SkyTint", new Color(.20f, .30f, .24f));
                sky.SetColor("_GroundColor", new Color(.08f, .10f, .07f));
                sky.SetFloat("_AtmosphereThickness", .92f);
                sky.SetFloat("_Exposure", .85f);
                RenderSettings.skybox = sky;
            }
            RenderSettings.fog = true;
            RenderSettings.fogMode = FogMode.ExponentialSquared;
            RenderSettings.fogColor = new Color(.34f, .41f, .30f);
            RenderSettings.fogDensity = .0037f;
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Trilight;
            RenderSettings.ambientSkyColor = new Color(.27f, .34f, .26f);
            RenderSettings.ambientEquatorColor = new Color(.15f, .19f, .11f);
            RenderSettings.ambientGroundColor = new Color(.045f, .055f, .025f);
            QualitySettings.shadows = ShadowQuality.All;
            QualitySettings.shadowDistance = 95f;
            QualitySettings.shadowResolution = ShadowResolution.High;
            QualitySettings.antiAliasing = 4;
            QualitySettings.anisotropicFiltering = AnisotropicFiltering.Enable;
            var sun = new GameObject("Low Nordic Sun").AddComponent<Light>();
            sun.type = LightType.Directional; sun.intensity = 1.18f; sun.color = new Color(1f, .61f, .34f); sun.shadows = LightShadows.Soft; sun.shadowStrength = .78f; sun.shadowBias = .04f; sun.shadowNormalBias = .3f; sun.transform.rotation = Quaternion.Euler(33, -42, 0);
        }

        private GameObject CreateFlatRock(string name, Vector3 position, Vector3 scale, Material mat, float yRotation)
        {
            var rock = GameObject.CreatePrimitive(PrimitiveType.Cube); rock.name = name; rock.transform.SetParent(ledges); rock.transform.SetPositionAndRotation(position, Quaternion.Euler(0, yRotation, 0)); rock.transform.localScale = scale; rock.GetComponent<Renderer>().sharedMaterial = mat; return rock;
        }

        private void CreateLedge(string name, Vector3 p, Vector3 s, Material mat, float rotation)
        {
            Vector3 radial = Vector3.ProjectOnPlane(p, Vector3.up).normalized;
            if (radial.sqrMagnitude > .01f)
            {
                // An inset slab overlaps the shell and the landing, reading as a carved terrace rather than a floating block.
                float radialYaw = 90f - Mathf.Atan2(radial.z, radial.x) * Mathf.Rad2Deg;
                var bridge = CreateFlatRock(name + " carved terrace", p - radial * 1.9f - Vector3.up * .12f, new Vector3(s.x * 1.25f, .62f, 5.1f), rockMid, radialYaw);
                bridge.transform.SetParent(ledges);
            }
            var ledge = CreateLandingRock(name, p, s, mat, rotation); ledge.transform.SetParent(ledges);
            // A broad top and downward taper visually anchor the landing to the mountain instead of creating an upward spike.
            var support = CreateRock(name + " attached rock shelf", p + new Vector3(0, -3.4f, 0), new Vector3(s.x * 1.45f, 6.8f, s.z * 1.45f), rockDark, 5, rotation);
            support.transform.SetParent(ledges);
            support.transform.localRotation = Quaternion.Euler(180f, rotation, 0f);
        }

        private GameObject CreateRock(string name, Vector3 position, Vector3 size, Material material, int sides, float rotation, bool createsCollider = true)
        {
            var obj = new GameObject(name); obj.transform.SetParent(mountain); obj.transform.SetPositionAndRotation(position, Quaternion.Euler(0, rotation, 0));
            var mesh = new Mesh { name = name + " mesh" }; var vertices = new List<Vector3>(); var triangles = new List<int>();
            float bottom = -size.y * .5f, top = size.y * .5f;
            vertices.Add(new Vector3(0, top, 0)); vertices.Add(new Vector3(0, bottom, 0));
            for (int i = 0; i < sides; i++) { float a = i * Mathf.PI * 2f / sides; float wobble = .78f + ((i * 17) % 5) * .055f; vertices.Add(new Vector3(Mathf.Cos(a) * size.x * .5f * wobble, bottom, Mathf.Sin(a) * size.z * .5f * wobble)); }
            for (int i = 0; i < sides; i++) { int n = i == sides - 1 ? 0 : i + 1; triangles.Add(0); triangles.Add(2 + i); triangles.Add(2 + n); triangles.Add(1); triangles.Add(2 + i); triangles.Add(2 + n); }
            mesh.SetVertices(vertices); mesh.SetTriangles(triangles, 0); mesh.RecalculateNormals();
            obj.AddComponent<MeshFilter>().sharedMesh = mesh; obj.AddComponent<MeshRenderer>().sharedMaterial = material;
            if (createsCollider) obj.AddComponent<MeshCollider>().sharedMesh = mesh;
            return obj;
        }

        private GameObject CreateLandingRock(string name, Vector3 position, Vector3 size, Material material, float yRotation, bool walkable = true)
        {
            const int sides = 7;
            var vertices = new List<Vector3> { new Vector3(0f, size.y * .5f, 0f), new Vector3(0f, -size.y * .5f, 0f) };
            for (int i = 0; i < sides; i++)
            {
                float angle = i * Mathf.PI * 2f / sides;
                float wobble = .86f + ((i * 19 + name.Length * 7) % 7) * .035f;
                float x = Mathf.Cos(angle) * size.x * .5f * wobble;
                float z = Mathf.Sin(angle) * size.z * .5f * wobble;
                vertices.Add(new Vector3(x, size.y * .5f, z));
                vertices.Add(new Vector3(x * 1.12f, -size.y * .5f, z * 1.12f));
            }
            var triangles = new List<int>();
            for (int i = 0; i < sides; i++)
            {
                int next = (i + 1) % sides;
                int top = 2 + i * 2, bottom = top + 1, nextTop = 2 + next * 2, nextBottom = nextTop + 1;
                triangles.Add(0); triangles.Add(nextTop); triangles.Add(top);
                triangles.Add(top); triangles.Add(nextTop); triangles.Add(bottom);
                triangles.Add(bottom); triangles.Add(nextTop); triangles.Add(nextBottom);
                triangles.Add(1); triangles.Add(bottom); triangles.Add(nextBottom);
            }
            var mesh = new Mesh { name = name + " low-poly landing mesh" };
            mesh.SetVertices(vertices); mesh.SetTriangles(triangles, 0); mesh.RecalculateBounds();
            var rock = new GameObject(name); rock.transform.SetParent(ledges); rock.transform.SetPositionAndRotation(position, Quaternion.Euler(0f, yRotation, 0f));
            rock.AddComponent<MeshFilter>().sharedMesh = mesh;
            rock.AddComponent<MeshRenderer>().sharedMaterial = material;
            if (walkable)
            {
                // A controlled primitive collider makes every landing reliable. The organic mesh remains visual only.
                var collider = rock.AddComponent<BoxCollider>();
                collider.center = Vector3.zero;
                collider.size = new Vector3(size.x * 1.04f, Mathf.Max(.38f, size.y), size.z * 1.04f);
                collider.sharedMaterial = surefootedStone;
            }
            return rock;
        }

        private void CreatePine(Vector3 p, float h)
        {
            var root = new GameObject("Dark Nordic pine"); root.transform.SetParent(vegetation); root.transform.SetPositionAndRotation(p, Quaternion.Euler(0f, p.x * 19f + p.z * 13f, 0f));
            var stem = GameObject.CreatePrimitive(PrimitiveType.Cylinder); stem.transform.SetParent(root.transform); stem.transform.localPosition = Vector3.up * h * .25f; stem.transform.localScale = new Vector3(.18f, h * .25f, .18f); stem.GetComponent<Renderer>().sharedMaterial = trunk; Destroy(stem.GetComponent<Collider>());
            var crownMaterial = Mathf.Repeat(p.x * .071f + p.z * .043f, 1f) > .52f ? needlesSun : needles;
            for (int i = 0; i < 4; i++) CreatePineCrown(root.transform, new Vector3(0f, h * (.32f + i * .16f), 0f), h * (.31f - i * .052f), h * .42f, crownMaterial);
        }

        private void CreatePineCrown(Transform parent, Vector3 localPosition, float radius, float height, Material material)
        {
            const int sides = 6;
            var vertices = new List<Vector3> { new Vector3(0f, height * .5f, 0f) };
            var triangles = new List<int>();
            for (int i = 0; i < sides; i++)
            {
                float angle = i * Mathf.PI * 2f / sides;
                float wobble = .82f + (i % 3) * .09f;
                vertices.Add(new Vector3(Mathf.Cos(angle) * radius * wobble, -height * .5f, Mathf.Sin(angle) * radius * wobble));
            }
            for (int i = 0; i < sides; i++) { int next = i == sides - 1 ? 0 : i + 1; triangles.Add(0); triangles.Add(1 + next); triangles.Add(1 + i); }
            var mesh = new Mesh { name = "Sparse pine crown mesh" }; mesh.SetVertices(vertices); mesh.SetTriangles(triangles, 0); mesh.RecalculateNormals();
            var crown = new GameObject("Sparse pine crown"); crown.transform.SetParent(parent); crown.transform.localPosition = localPosition;
            crown.AddComponent<MeshFilter>().sharedMesh = mesh; crown.AddComponent<MeshRenderer>().sharedMaterial = material;
        }

        private void CreateAlpineTuft(Vector3 position, float size, float rotation)
        {
            var tuft = new GameObject("Alpine grass tuft"); tuft.transform.SetParent(vegetation); tuft.transform.SetPositionAndRotation(position, Quaternion.Euler(0f, rotation, 0f));
            for (int i = 0; i < 3; i++)
            {
                var blade = GameObject.CreatePrimitive(PrimitiveType.Cube); blade.transform.SetParent(tuft.transform);
                blade.transform.localPosition = new Vector3((i - 1) * size * .22f, size * .35f, (i % 2 == 0 ? .05f : -.08f));
                blade.transform.localRotation = Quaternion.Euler((i - 1) * 13f, i * 29f, (i - 1) * 16f);
                blade.transform.localScale = new Vector3(size * .08f, size * .7f, size * .05f);
                blade.GetComponent<Renderer>().sharedMaterial = grass;
                Destroy(blade.GetComponent<Collider>());
            }
        }

        private void CreateShrub(Vector3 position, float size, float rotation)
        {
            var root = new GameObject("Heather and juniper"); root.transform.SetParent(vegetation); root.transform.SetPositionAndRotation(position, Quaternion.Euler(0f, rotation, 0f));
            for (int i = 0; i < 3; i++)
            {
                var crown = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                crown.transform.SetParent(root.transform);
                crown.transform.localPosition = new Vector3((i - 1) * size * .42f, size * .28f, (i % 2 == 0 ? .13f : -.15f) * size);
                crown.transform.localScale = new Vector3(size * .8f, size * .6f, size * .72f);
                crown.GetComponent<Renderer>().sharedMaterial = i == 1 ? heather : (i == 0 ? ledgeTop : needles);
                Destroy(crown.GetComponent<Collider>());
            }
        }

        private void CreateTrailMarker(Vector3 position, float rotation)
        {
            var marker = new GameObject("Warm route marker"); marker.transform.SetParent(ledges); marker.transform.SetPositionAndRotation(position + Vector3.up * .55f, Quaternion.Euler(0f, rotation, 0f));
            var pole = GameObject.CreatePrimitive(PrimitiveType.Cylinder); pole.transform.SetParent(marker.transform); pole.transform.localPosition = Vector3.up * .38f; pole.transform.localScale = new Vector3(.045f, .42f, .045f); pole.GetComponent<Renderer>().sharedMaterial = trailMarker; Destroy(pole.GetComponent<Collider>());
            var pennant = GameObject.CreatePrimitive(PrimitiveType.Cube); pennant.transform.SetParent(marker.transform); pennant.transform.localPosition = new Vector3(.23f, .62f, 0f); pennant.transform.localScale = new Vector3(.45f, .24f, .03f); pennant.GetComponent<Renderer>().sharedMaterial = trailMarker; Destroy(pennant.GetComponent<Collider>());
        }

        private void CreateRouteBeacon(Vector3 position, float rotation)
        {
            var beacon = new GameObject("Warm route beacon"); beacon.transform.SetParent(ledges); beacon.transform.SetPositionAndRotation(position + Vector3.up * .48f, Quaternion.Euler(0f, rotation, 0f));
            var pole = GameObject.CreatePrimitive(PrimitiveType.Cylinder); pole.transform.SetParent(beacon.transform); pole.transform.localPosition = Vector3.up * .38f; pole.transform.localScale = new Vector3(.05f, .42f, .05f); pole.GetComponent<Renderer>().sharedMaterial = trunk; Destroy(pole.GetComponent<Collider>());
            var ember = GameObject.CreatePrimitive(PrimitiveType.Sphere); ember.transform.SetParent(beacon.transform); ember.transform.localPosition = Vector3.up * .82f; ember.transform.localScale = Vector3.one * .18f; ember.GetComponent<Renderer>().sharedMaterial = fire; Destroy(ember.GetComponent<Collider>());
            var glow = beacon.AddComponent<Light>(); glow.type = LightType.Point; glow.color = new Color(1f, .30f, .08f); glow.intensity = 1.35f; glow.range = 5.5f; glow.shadows = LightShadows.None;
        }
    }
}
